## Pandas - 01 Introduction

In [5]:
import pandas as pd

pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.'],
              'Jim': ['Great!', 'So bad.']},
              index=['Product A', 'Product B'])

                     Bob           Sue      Jim
Product A    I liked it.  Pretty good.   Great!
Product B  It was awful.        Bland.  So bad.

In [14]:
import pandas as pd

pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], 
          name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [11]:
import pandas as pd

df = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

## Pandas - 02 Indexing, Selecting & Assigning

In [150]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
# data_source.loc[0]
data_source.iloc[0]
# referencing row 0, all columns

Gender                                  Male
Age                                       27
Occupation                 Software Engineer
Sleep Duration                           6.1
Quality of Sleep                           6
Physical Activity Level                   42
Stress Level                               6
BMI Category                      Overweight
Blood Pressure                        126/83
Heart Rate                                77
Daily Steps                             4200
Sleep Disorder                           NaN
Name: 1, dtype: object

In [145]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
# data_source.loc[:, "Occupation"]
data_source.iloc[:, 2]
# referencing column "Occupation", all rows

Person ID
1         Software Engineer
2                    Doctor
3                    Doctor
4      Sales Representative
5      Sales Representative
               ...
370                   Nurse
371                   Nurse
372                   Nurse
373                   Nurse
374                   Nurse
Name: Occupation, Length: 374, dtype: str

In [193]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
data_source.set_index('Occupation', inplace=True)
data_source

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Occupation,,,,,,,,,,,
Software Engineer,Male,27,6.1,6,42,6,Overweight,126/83,77,4200,NaN
Doctor,Male,28,6.2,6,60,8,Normal,125/80,75,10000,NaN
Doctor,Male,28,6.2,6,60,8,Normal,125/80,75,10000,NaN
Sales Representative,Male,28,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
Sales Representative,Male,28,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [192]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
temp = data_source[(data_source["BMI Category"] == "Normal") &
                   (data_source["Occupation"] == "Doctor")]
temp

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
76,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000,NaN
77,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000,NaN
78,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000,NaN
79,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000,NaN
80,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000,NaN

In [203]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
temp = data_source[data_source.Occupation.isin(["Doctor", "Nurse"])]
temp

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [208]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
data_source["Occupation"] = "Doctor"
data_source

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
1,Male,27,Doctor,6.1,6,42,6,Overweight,126/83,77,4200,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
4,Male,28,Doctor,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,28,Doctor,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
370,Female,59,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Doctor,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
374,Female,59,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

## 03 - Summary Functions and Maps

In [214]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
data_source["Heart Rate"].describe()

count    374.000000
mean      70.165775
std        4.135676
min       65.000000
25%       68.000000
50%       70.000000
75%       72.000000
max       86.000000
Name: Heart Rate, dtype: float64

In [215]:
import pandas as pd

data_source = pd.read_csv(r"D:\DS_Crumbs\DS_prep\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
data_source["Occupation"].unique()

<StringArray>
[   'Software Engineer',               'Doctor', 'Sales Representative',
              'Teacher',                'Nurse',             'Engineer',
           'Accountant',            'Scientist',               'Lawyer',
          'Salesperson',              'Manager']
Length: 11, dtype: str