## 01 - Introduction

### Data Frame
A Data Frame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row and a column.\
`.DataFrame()`

In [13]:
import pandas as pd

pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.'],
              'Jim': ['Great!', 'So bad.']},
              index=['Product A', 'Product B'])

                     Bob           Sue      Jim
Product A    I liked it.  Pretty good.   Great!
Product B  It was awful.        Bland.  So bad.

### Series
A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. \
A Series is, in essence, a single column of a DataFrame. Assign row labels to the Series the same way as before, using an `index` parameter. \
However, a Series does not have a column name, it only has one overall `name`.  \
`.Series()`

In [64]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], 
          name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

### Importing a Dataset
So a CSV file is a table of values separated by commas. Hence the name: "Comma-Separated Values", or CSV. \
We'll use the `.read_csv()` function to read the data and turn it into a DataFrame.

In [65]:
df = pd.read_csv(r"..\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
df

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

## 02 - Indexing, Selecting & Assigning

In [59]:
import pandas as pd
df = pd.read_csv(r"..\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
df['BMI Category'] = df['BMI Category'].replace('Normal Weight', 'Normal')

### Indexing

- **Index-based Selection** \
The first is index-based selection: selecting data based on its numerical position(base 10) in the data. \
`.iloc[]`

In [60]:
df.iloc[0]
# selecting the first row using index [0], all columns

Gender                                  Male
Age                                       27
Occupation                 Software Engineer
Sleep Duration                           6.1
Quality of Sleep                           6
Physical Activity Level                   42
Stress Level                               6
BMI Category                      Overweight
Blood Pressure                        126/83
Heart Rate                                77
Daily Steps                             4200
Sleep Disorder                           NaN
Name: 1, dtype: object

- **Label-based Selection** \
The second paradigm is the one followed by the `loc` : label-based selection. \
In this paradigm, it's the data index value(aka. the column label), not its numerical position, which matters. \
`.loc[]`

In [41]:
df.loc[:, "Occupation"]
# referencing the Occupation column using label selection "Occupation", all rows

Person ID
1         Software Engineer
2                    Doctor
3                    Doctor
4      Sales Representative
5      Sales Representative
               ...
370                   Nurse
371                   Nurse
372                   Nurse
373                   Nurse
374                   Nurse
Name: Occupation, Length: 374, dtype: str

- **Manipulating the Index** \
Label-based selection derives its power from the labels in the index. Usually* the available index label is not immutable. \
We can manipulate the index labels in any way we see fit. \
`.set_index()`

In [96]:
# df.set_index("Occupation", inplace=True)
df

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Occupation,,,,,,,,,,,
Software Engineer,Male,27,6.1,6,42,6,Overweight,126/83,77,4200,NaN
Doctor,Male,28,6.2,6,60,8,Normal,125/80,75,10000,NaN
Doctor,Male,28,6.2,6,60,8,Normal,125/80,75,10000,NaN
Sales Representative,Male,28,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
Sales Representative,Male,28,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
Nurse,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

### Conditional Selection

We can use the common Python built-in operations and methods, for example here is one from comparison operators.

In [74]:
# df[df['BMI Category'] == 'Normal']
df[df['Age'] <= 30]

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
11,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,NaN
12,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
13,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000,NaN
14,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,NaN
15,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,NaN
16,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,NaN
17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
18,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000,Sleep Apnea
19,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Insomnia
20,Male,30,Doctor,7.6,7,75,6,Normal,120/80,70,8000,NaN
21,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,NaN
22,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,NaN
23,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,NaN
24,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000,NaN
25,Male,30,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
26,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,NaN
27,Male,30,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
28,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,NaN
29,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,NaN
30,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000,NaN
31,Female,30,Nurse,6.4,5,35,7,Normal Weight,130/86,78,4100,Sleep Apnea
32,Female,30,Nurse,6.4,5,35,7,Normal Weight,130/86,78,4100,Insomnia

- **is in** \
The first is `isin`. `isin` lets you select data whose value "is in" the referenced list of values.

In [79]:
df[df["Occupation"].isin(["Doctor", "Nurse"])]

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

- **is null** \
The second is `isnull` (and its companion `notnull`). These methods let you highlight values which are (or are not) empty (`NaN`).

In [86]:
# df.loc[df['Sleep Disorder'].isnull()]
df.loc[df['Sleep Disorder'].notnull()]

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
4,Male,,Doctor,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,,Doctor,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
6,Male,,Doctor,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
7,Male,,Doctor,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
17,Female,,Doctor,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
370,Female,,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,,Doctor,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
374,Female,,Doctor,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

### Assigning Data

In [90]:
# df["Occupation"] = "Doctor"
df["Age"] = df["Age"] + 10
df.head(10)

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
1,Male,37,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
2,Male,38,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,Male,38,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
4,Male,38,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,38,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
6,Male,38,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
7,Male,39,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
8,Male,39,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
9,Male,39,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
10,Male,39,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None

## 03 - Summary Functions and Maps

### Summary Functions

In [1]:
import pandas as pd

df = pd.read_csv(r"..\data\Sleep_health_and_lifestyle_dataset.csv", index_col=0)
df['BMI Category'] = df['BMI Category'].replace('Normal Weight', 'Normal')
df.loc[df['Sleep Disorder'].isnull(), 'Sleep Disorder'] = 'None'

In [119]:
df["Heart Rate"].describe()

count    374.000000
mean      70.165775
std        4.135676
min       65.000000
25%       68.000000
50%       70.000000
75%       72.000000
max       86.000000
Name: Heart Rate, dtype: float64

In [118]:
df["Occupation"].unique()

<StringArray>
[   'Software Engineer',               'Doctor', 'Sales Representative',
              'Teacher',                'Nurse',             'Engineer',
           'Accountant',            'Scientist',               'Lawyer',
          'Salesperson',              'Manager']
Length: 11, dtype: str

In [117]:
df["Occupation"].value_counts()

Occupation
Nurse                   73
Doctor                  71
Engineer                63
Lawyer                  47
Teacher                 40
Accountant              37
Salesperson             32
Software Engineer        4
Scientist                4
Sales Representative     2
Manager                  1
Name: count, dtype: int64

### Maps
A map is a term for a function that takes one set of values and "maps" them to another set of values. \
We often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later.

In [180]:
def format_sleep_duration(duration):
    temp = str(duration).split('.')
    temp[1] = str(int(float("0." + temp[1]) * 60))
    return f'{temp[0]}h {temp[1]}m'

df['Sleep Duration'].map(lambda x: format_sleep_duration(x))

Person ID
1       6h 6m
2      6h 12m
3      6h 12m
4      5h 54m
5      5h 54m
        ...
370     8h 6m
371     8h 0m
372     8h 6m
373     8h 6m
374     8h 6m
Name: Sleep Duration, Length: 374, dtype: str

# 04 - Grouping and Sorting

### Group By

`groupby()` splits a DataFrame into groups based on one or more columns.

Use it when you want to:
- group rows by a category
- calculate summary values for each group
- apply functions like `sum()`, `mean()`, `min()`, `max()`, or `agg()`

In [3]:
import numpy as np
df.groupby(['Occupation'])['Quality of Sleep'].agg([len, np.mean, min, max])
# This groups the data by `Occupation` and returns basic sleep statistics for each occupation.

                      len      mean  min  max
Occupation
Accountant             37  7.891892    7    9
Doctor                 71  6.647887    6    9
Engineer               63  8.412698    5    9
Lawyer                 47  7.893617    7    8
Manager                 1  7.000000    7    7
Nurse                  73  7.369863    5    9
Sales Representative    2  4.000000    4    4
Salesperson            32  6.000000    6    6
Scientist               4  5.000000    4    6
Software Engineer       4  6.500000    4    8
Teacher                40  6.975000    5    8

In [4]:
df.groupby(['Quality of Sleep'])['Stress Level'].agg([len, np.mean, max, min, lambda x: max(x)-min(x)])

                  len      mean  max  min  <lambda_0>
Quality of Sleep
4                   5  8.000000    8    8           0
5                   7  7.000000    7    7           0
6                 105  7.580952    8    6           2
7                  77  5.350649    7    4           3
8                 109  4.605505    6    3           3
9                  71  3.028169    4    3           1

In [5]:
df

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
Person ID,,,,,,,,,,,,
1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea